More fixes (#310)
* Fix music playing when master is 0

* Update cherry-pick workflow

* Fix missing }}

* Dont allow duplicates

* Dont allow duplicate selected with multi-select

diff --git a/.github/workflows/cherry_pick_to_all_versions.yml b/.github/workflows/cherry_pick_to_all_versions.yml
--- a/.github/workflows/cherry_pick_to_all_versions.yml
+++ b/.github/workflows/cherry_pick_to_all_versions.yml
@@ -7,6 +7,10 @@ on:
         description: 'Commit to cherry pick'
         required: true
         type: string
+      versions:
+        description: 'Minecraft versions to cherry pick to (comma separated)'
+        required: false
+        type: string
 
 jobs:
   apply_cherry_pick:
@@ -24,18 +28,26 @@ jobs:
       - name: Create and publish branches
         env:
           GH_TOKEN: ${{ secrets.PUBLISH_GITHUB_TOKEN }}
-          COMMIT_ID: ${{ github.event.inputs.commit_id }}
+          COMMIT_IDS: ${{ github.event.inputs.commit_ids }}
+          VERSIONS: ${{ github.event.inputs.versions }}
         run: |
-          count=0
           regex_prefix="origin\/versions\/"
-          branches=$(git branch -r | tr -d ' '); while read -r branch; do
+          all_branches=$(git branch -r | tr -d ' ')
+          if [[ -z $VERSIONS ]]; then
+            target_branches=$all_branches
+          else
+            target_branches=$(echo "$versions" | sed 's/,/\n/g')
+          fi
+          
+          branches=$target_branches; while read -r branch; do
                   if [[ "$branch" =~ $regex_prefix.* ]]; then
                           version=${branch:${#regex_prefix}-2}
                           new_branch=vcp/$version-$COMMIT_ID
                           git switch -c $new_branch $branch
-                          (git cherry-pick $COMMIT_ID && git push -u origin $new_branch) || (echo "Failed to cherry pick into version branch $branch" && git cherry-pick --abort && continue)
-                          gh pr create -B refs/heads/versions/$version --title "$version: Cherry pick commit $COMMIT_ID" --body "Cherry-pick" || (echo "Failed to create PR for $new_branch" && continue)
-                          count=$((count + 1))
+                          for COMMIT_ID in ${COMMIT_IDS//,/ }
+                          do
+                            (git cherry-pick $COMMIT_ID --strategy-option=theirs && git push -u origin $new_branch) || (echo "Failed to cherry pick $COMMIT_ID into version branch $branch" && git cherry-pick --abort && continue)
+                          done
+                          gh pr create -B refs/heads/versions/$version --title "$version: Cherry pick commit" --body "Cherry-pick commits: $COMMIT_IDS" || (echo "Failed to create PR for $new_branch" && continue)
                   fi
           done <<< "$branches"
-          echo "Created $count PRs"
