Update cherry pick script

diff --git a/.github/workflows/cherry_pick_to_all_versions.yml b/.github/workflows/cherry_pick_to_all_versions.yml
--- a/.github/workflows/cherry_pick_to_all_versions.yml
+++ b/.github/workflows/cherry_pick_to_all_versions.yml
@@ -25,16 +25,17 @@ jobs:
         env:
           GITHUB_TOKEN: ${{ secrets.PUBLISH_GITHUB_TOKEN }}
           GH_TOKEN: ${{ github.token }}
+          COMMIT_ID: ${{ github.event.inputs.commit_id }}
         run: |
           count=0
           regex_prefix="origin\/versions\/"
           branches=$(git branch -r | tr -d ' '); while read -r branch; do
                   if [[ "$branch" =~ $regex_prefix.* ]]; then
                           version=${branch:${#regex_prefix}-2}
-                          new_branch=vcp/$version
+                          new_branch=vcp/$version-$COMMIT_ID
                           git switch -c $new_branch $branch
-                          (git cherry-pick ${{ github.event.inputs.commit_id }} && git push -u origin $new_branch) || (echo "Failed to cherry pick into version branch $branch" && git cherry-pick --abort && continue)
-                          gh pr create -B refs/heads/versions/$version --title "$branch: Cherry pick commit ${{ github.event.inputs.commit_id }}" --body "Cherry-pick" || (echo "Failed to create PR for $new_branch" && continue)
+                          (git cherry-pick $COMMIT_ID && git push -u origin $new_branch) || (echo "Failed to cherry pick into version branch $branch" && git cherry-pick --abort && continue)
+                          gh pr create -B refs/heads/versions/$version --title "$branch: Cherry pick commit $COMMIT_ID" --body "Cherry-pick" || (echo "Failed to create PR for $new_branch" && continue)
                           count=$((count + 1))
                   fi
           done <<< "$branches"
