Update cherry pick script

diff --git a/.github/workflows/cherry_pick_to_all_versions.yml b/.github/workflows/cherry_pick_to_all_versions.yml
--- a/.github/workflows/cherry_pick_to_all_versions.yml
+++ b/.github/workflows/cherry_pick_to_all_versions.yml
@@ -33,7 +33,7 @@ jobs:
                           new_branch="vcp/${branch:${#regex_prefix}-2}"
                           git switch -c $new_branch $branch
                           git cherry-pick ${{ github.event.inputs.commit_id }} || (echo "Failed to cherry pick into version branch $branch" && git cherry-pick --abort && continue)
-                          gh pr create --base $branch --title "$branch: Cherry pick commit ${{ github.event.inputs.commit_id }}" --body "" || (echo "Failed to create PR for $new_branch" && continue)
+                          gh pr create --head --base $branch --title "$branch: Cherry pick commit ${{ github.event.inputs.commit_id }}" --body "" || (echo "Failed to create PR for $new_branch" && continue)
                           count=$((count + 1))
                   fi
           done <<< "$branches"
