Update cherry-pick

diff --git a/.github/workflows/cherry_pick_to_all_versions.yml b/.github/workflows/cherry_pick_to_all_versions.yml
--- a/.github/workflows/cherry_pick_to_all_versions.yml
+++ b/.github/workflows/cherry_pick_to_all_versions.yml
@@ -39,14 +39,14 @@ jobs:
           else
             target_branches=$(echo "$versions" | sed 's/,/\n/g')
           fi
-          COMMIT_IDS=$(echo "$COMMIT_IDS" | sed 's/,/ /g')
+          COMMIT_TARGETS=$(echo "$COMMIT_IDS" | sed 's/,/ /g')
           
           branches=$target_branches; while read -r branch; do
                   if [[ "$branch" =~ $regex_prefix.* ]]; then
                           version=${branch:${#regex_prefix}-2}
                           new_branch=vcp/$version-$COMMIT_IDS
                           git switch -c $new_branch $branch
-                          (git cherry-pick $COMMIT_IDS --strategy-option=theirs && git push -u origin $new_branch) || (echo "Failed to cherry pick $COMMIT_ID into version branch $branch" && git cherry-pick --abort && continue)
+                          (git cherry-pick $COMMIT_TARGETS --strategy-option=theirs && git push -u origin $new_branch) || (echo "Failed to cherry pick $COMMIT_ID into version branch $branch" && git cherry-pick --abort && continue)
                           gh pr create -B refs/heads/versions/$version --title "$version: Cherry pick commit" --body "Cherry-pick commits: $COMMIT_IDS" || (echo "Failed to create PR for $new_branch" && continue)
                   fi
           done <<< "$branches"
