Update cherry pick script

diff --git a/.github/workflows/cherry_pick_to_all_versions.yml b/.github/workflows/cherry_pick_to_all_versions.yml
--- a/.github/workflows/cherry_pick_to_all_versions.yml
+++ b/.github/workflows/cherry_pick_to_all_versions.yml
@@ -31,8 +31,8 @@ jobs:
                   if [[ "$branch" =~ $regex_prefix.* ]]; then
                           new_branch="vcp/${branch:${#regex_prefix}-2}"
                           git switch -c $new_branch $branch
-                          git cherry-pick ${{ github.event.inputs.commit_id }} || continue
-                          gh pr create --base $branch || echo "Failed to create PR for $new_branch"
+                          git cherry-pick ${{ github.event.inputs.commit_id }} || (git cherry-pick --abort && continue)
+                          gh pr create --base $branch || (echo "Failed to create PR for $new_branch" && continue)
                           count=$((count + 1))
                   fi
           done <<< "$branches"
