Print first

diff --git a/.github/workflows/validate.yml b/.github/workflows/validate.yml
--- a/.github/workflows/validate.yml
+++ b/.github/workflows/validate.yml
@@ -11,4 +11,4 @@ jobs:
     steps:
       - name: Test branch name
         if: !contains(github.head_ref, '.') # Is version branch
-        run: exit 1; echo "Cannot PR version branch into master"
+        run: echo "Cannot PR version branch into master"; exit 1
